    create table admins (
       email varchar(255) not null,
        created_at timestamp,
        deleted_at timestamp,
        invitation_token varchar(255),
        name varchar(255) not null,
        password varchar(255) not null,
        reset_token varchar(255),
        surname varchar(255) not null,
        updated_at timestamp,
        username varchar(255) not null,
        primary key (email)
    );

    create table class_ut (
       name varchar(255) not null,
        category JSONB,
        created_at timestamp,
        date date,
        deleted_at timestamp,
        description TEXT,
        difficulty varchar(255),
        updated_at timestamp,
        uri varchar(255),
        primary key (name)
    );

    create table hints (
       id int8 generated by default as identity,
        content TEXT not null,
        created_at timestamp,
        deleted_at timestamp,
        image_uri varchar(255),
        "order" int4 not null,
        type varchar(255) not null,
        updated_at timestamp,
        admin_email varchar(255),
        class_ut_name varchar(255),
        primary key (id)
    );

    alter table if exists admins
       add constraint UK_mi8vkhus4xbdbqcac2jm4spvd unique (username);

    alter table if exists hints
       add constraint FKajn8opv2fb9me93mpodf5pdup
       foreign key (admin_email)
       references admins;

    alter table if exists hints
       add constraint FKm7bkja5pb51ge0hfsrm0ieyoj
       foreign key (class_ut_name)
       references class_ut;