server:
  error:
    include-message: always

spring:
  flyway:
    enabled: true # <-- DA FALSE A TRUE: ATTIVA FLYWAY
    # CRUCIALE: Dice a Flyway di registrare la migrazione V1 come eseguita,
    # dato che le tabelle esistono già.
    baseline-on-migrate: true
    # Assicurati che il percorso sia corretto:
    locations: classpath:db/migrations

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://t1-postgres-db:5432/manvsclass}
    username: ${POSTGRES_USERNAME:t1-g11}
    password: ${POSTGRES_PASSWORD:'947!"p1Yv;qf'}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

t1:
  upload-dir: ${UPLOAD_DIR:C:\Users\rosa9\D6-taskR2\T1-G11\applicazione\manvsclass\FilesUpload}

logging:
  level:
    org:
      springframework: